server:
  port: 7799
  servlet:
    context-path: /ssjy
  tomcat:
    max-threads: 800

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssjy?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: test
    password: test
    #driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ##每次启动都重新创建数据库表
      # create:每次运行程序时，都会重新创建表，故而数据会丢失
      # create-drop：每次运行程序时会先创建表结构，然后待程序结束时清空表
      # upadte：每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新（推荐使用）
      # validate：运行程序会校验数据与数据库的字段类型是否相同，字段不同会报错
      # none: 禁用DDL处理
      ddl-auto: update
    show-sql: true

  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false



